AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 200

Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
  CountComments: false # count full line comments?
  Max: 200

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
